---
title: "Projet-C : Tri par tas"
author: "Vincent ROCHER"
date: "22 février 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: default
    highlight: espresso

---

# But du programme

Le but du programme est de trier une liste d'entier présent dans un fichier dans l'ordre croissant. Le programme utilise des structures particulières de programmation pour fonctionner :

* Un tas représentant un arbre binaire partiellement ordonné (représenté par un tableau).
* Pour chaque noeud $n$, son enfant gauche est placé en $2n$ et son enfant droite en $2n+1$.
* Ce tas doit être organisé en Tas max, soit la plus grande valeur comme racine (en premier indice).

# Fichiers

* __`README.html`__ : Fichier README.
* __`Makefile`__ : Fichier de compilation.
* __`main.c`__ : Fichier principal du programme.
* __`fichier.c`__ : Fichier contenant les fonctions nécessaire à la lecture et écriture de fichiers.
* __`fichier.h`__ : Fichier d'en-tête de __`fichier.c`__.
* __`triTas.c`__ : Fichier contenant les fonctions d'insertion du Tas, de tri et de tamisage.
* __`triTas.h`__ : Fichier d'en-tête de __`triTas.c`__.
* __`sample/`__ : Dossier contenant les fichiers utilisés pour les tests du programme, avec $10$,$20$,$50$,$500$ et $5000$ entiers (version non triée, croissante et décroissante).

#Fonctions

##__`fichier.c`__

__`fichier.c`__ contient 3 fonctions :

```c
FILE* OuvrirFichier(char*) ;
void EcrireFichier(char*,int*,int) ;
int GetNombreElements(FILE *) ;
```

* `OuvrirFichier` Ouvre un fichier en mode lecture.
    * __Input__ : Un nom de fichier.
    * __Output__ : Un pointeur de fichier.
* `EcrireFichier` Va écrire le résultat du Tas trié dans un fichier.
    * __Input__ : Un nom de fichier, le Tas et la taille du tas.
* `GetNombreElements` Retourne le nombre d'éléments présents dans le fichier donné en argument.
    * __Input__ : Un pointeur de fichier.
    * __Output__ : Un entier correspondant au nombre d'entiers présents dans le fichier.

##__`triTas.h`__

En plus de contenir les en-têtes de fonctions, __`triTas.h`__ va définir un type particulier :
```c
typedef void (*Pfonction)(int*,int,int);
```
ce `Pfonction` va contenir un pointeur vers une fonction, ce qui va permettre au programme de choisir entre la fonction recursive ou itérative du tamisage (`Tamiser_max_rec` ou `Tamiser_max`).

##__`triTas.c`__

__`triTas.c`__ contient 9 fonctions :

```c
int* ConstruireTableau(FILE *,int) ;
void AfficherTableau(int*,int) ;
int EnfantGauche(int) ;
int EnfantDroite(int) ;
void Echange(int*,int*) ;
void Tamiser_max_rec(int*,int,int) ;
void Tamiser_max(int*,int,int) ;
void ConstruireTas(int*,int,Pfonction Tamiser) ;
void TriTas(int*,int,Pfonction Tamiser) ;
```

* `ConstruireTableau` va construire un tas initial (ne suivant pas les règles d'un arbre binaire complet partiellement ordonné) à partir d'une liste d'entier présent dans un fichier.
    * __Input__ : Un pointeur de fichier, ainsi que le nombre d'éléments présents dans le fichier.
    * __Output__ : Un tableau contenant les entiers.
* `AfficherTableau` sert dans le cas ou l'utilisateur ne fourni pas de fichier de sortie en argument.
    * __Input__ : Un tableau d'entier et la taille du tableau.
    * __Output__ : Affichage du tas sur la sortie standard.
* `EnfantGauche` et `EnfantDroite` vont servir à renvoyer la position des enfants pour une racine donnée.
    * __Input__ : Un entier correspondant à la position de la racine dans le tableau.
    * __Output__ : Un entier correspondant à la position de l'enfant droite ou gauche de la racine dans le tableau.
* `Echange` va échanger deux éléments dans un tableau.
    * __Input__ : Deux références correspondant à l'espace mémoire de deux entiers.
* `Tamiser_max_rec` et `Tamiser_max` sont les deux fonctions les plus importantes du programme (usage récursif ou itératif). Elles vont replacer un entier correctement dans le Tas en fonction des règles établies (Tas max ou tas min), en le comparant avec ses enfants, et en faisant l'échange si besoin est jusqu'à ce que l'entier soit correctement placé dans le tableau.
    * __Input__ : Le tas, la position de l'entier dans le tas et la taille du tableau.
* `ConstruireTas` va construire le tas suivant les règles établies (tas max ou min) pour représenter l'arbre correctement (voir partie but du programme).
    * __Input__ : La liste des entiers sous forme de tableau, la taille du tableau et la fonction à utiliser pour construire le tas (`Tamiser_max_rec` ou `Tamiser_max`).
* `TriTas` va trier le tas dans l'ordre croissant.
    * __Input__ : Le tas ordonné de façon a représenter un arbre binaire partiellement ordonné (`ConstruireTas`), la taille du Tas et la fonction à utiliser pour trier le tas (`Tamiser_max_rec` ou `Tamiser_max`).

#Déroulement du programme (`main.c`)

Le fonctionnement de `main.c` s'effectue de la façon suivante :

* On récupère les options que l'utilisateur à passé en argument : `Usage: ./triTas [-r (recursive usage)] [-i input file name (non optional)] [-o output file name (optional)]`
* Si l'utilisateur n'indique pas de fichier de sortie, le tri sera affiché sur la sortie standard avec `AfficherTableau`.
* Si l'utilisateur choisit l'option `-r`, on fera appel à la fonction `Tamiser_max_rec`, sinon par défaut le programme utilise la fonction `Tamiser_max`.
* On ouvre le fichier portant le nom donné en argument (`OuvrirFichier`).
* On détermine le nombre d'éléments présents dans le fichier (`GetNombreElements`).
* On construit le tableau à partir des entiers contenus dans le fichier (`ConstruireTableau`).
* Ensuite on construit le Tas initial (`ConstruireTas`) en faisant appel à la fonction de tamisage définie au début du programme.
    * Appel de la fonction `Tamiser_max` ou `Tamiser_max_rec` de la moitié du tableau jusqu'au premier indice (les éléments situés dans la deuxième moitié du tableau étant les feuilles de l'arbre).
* On réalise ensuite le tri du Tas (croissant) à l'aide de la fonction `TriTas`.
    * `Echange` du premier élément du tableau (le max) avec le dernier
    * Puis appel de la fonction `Tamiser_max` ou `Tamiser_max_rec` de $n-1$ à $1$ (équivaut à considérer un nouveau tas d'entiers plus petit de $1$ à chaque tour, ou les entiers situés entre l'indice du compteur et $n$ sont triés). 
* On écrit ensuite le résultat du tri dans le fichier fourni en argument (`EcrireFichier`).

#Tests avec les fichiers de `sample/`

##Execution du programme avec la fonction récursive
|__Entiers__|10|20|50|500|5000|
|---|---|---|---|---|---|
|__Non trié__|$3.26^{-6}$ sec|$4.81^{-6}$ sec|$9.68^{-6}$ sec|$10.447^{-5}$ sec|$12.782^{-3}$ sec|
|__Croissant__|$3.37^{-6}$ sec|$4.73^{-6}$ sec|$9.96^{-6}$ sec|$10.109^{-5}$ sec|$11.143^{-3}$ sec|
|__Décroissant__|$3.14^{-6}$ sec|$4.32^{-6}$ sec|$8.65^{-6}$ sec|$8.983^{-5}$ sec|$11.109^{-3}$ sec|


##Execution du programme avec la fonction itérative
|__Entiers__|10|20|50|500|5000|
|---|---|---|---|---|---|
|__Non trié__|$2.86^{-6}$ sec|$4.19^{-6}$ sec|$8.24^{-6}$ sec|$8.623^{-5}$ sec|$8.504^{-3}$ sec|
|__Croissant__|$2.87^{-6}$ sec|$4.02^{-6}$ sec|$8.18^{-6}$ sec|$8.268^{-5}$ sec|$8.636^{-3}$ sec|
|__Décroissant__|$2.89^{-6}$ sec|$3.69^{-6}$ sec|$7.51^{-6}$ sec|$8.282^{-5}$ sec|$9.034^{-3}$ sec|

##Commentaires

Pour construire ces deux tableaux, chaque test a été répété $1000$ fois dans le but de produire un temps moyen cohérent. 

Ce qu'on peut constater, c'est que peu importe le nombre d'entier, la fonction itérative est toujours plus rapide que la fonction récursive. 

Même si la fonction récursive peut faire appel à un nombre plus restreint de fonctions que l'itératif de tour de boucle (notamment lorsque les entiers sont déjà triés), il est probable que la différence de temps d'éxecution soit due à la plus forte consommation en mémoire et en temps d'un appel de fonction comparé à un tour de boucle.

À priori, il vaut toujours mieux utiliser la fonction itérative, qui est plus rapide, mais même pour un grand nombre d'entier à trier, le temps d'éexecution est très court. Ceci peut s'expliquer par la complexité du tri, qui est de $n \times log(n)$, et non pas quadratique ($n^2$).

Pour trier des entiers déjà triés, la fonction recursive semble légèrement plus performante lorsque les entiers sont triés dans l'ordre décroissant.

##Profilage du script avec `gprof`

###Profilage du programme avec la fonction récursive ($5000000$ entiers)

####Profil général du programme

```c
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
 60.64      0.81     0.81  7499999     0.00     0.00  Tamiser_max_rec
 12.73      0.98     0.17 105867450     0.00     0.00  Echange
  7.49      1.08     0.10 108367450     0.00     0.00  EnfantGauche
  5.99      1.16     0.08 108367450     0.00     0.00  EnfantDroite
  4.49      1.22     0.06                             Tamiser_max
  3.74      1.27     0.05        1    50.16   828.62  TriTas
  2.25      1.30     0.03        1    30.09    30.09  ConstruireTableau
  2.25      1.33     0.03        1    30.09    30.09  EcrireFichier
  0.75      1.34     0.01        1    10.03    10.03  GetNombreElements
  0.00      1.34     0.00        1     0.00   385.20  ConstruireTas
  0.00      1.34     0.00        1     0.00     0.00  OuvrirFichier
```

####Graphe d'appel pour la fonction `Tamiser_max_rec`

```c
granularity: each sample hit covers 2 byte(s) for 0.74% of 1.34 seconds

index % time    self  children    called     name
                                                 <spontaneous>
                             100867451             Tamiser_max_rec [2]
                0.27    0.11 2500000/7499999     ConstruireTas [4]
                0.54    0.23 4999999/7499999     TriTas [3]
[2]     86.0    0.81    0.34 7499999+100867451 Tamiser_max_rec [2]
                0.16    0.00 100867451/105867450     Echange [5]
                0.10    0.00 108367450/108367450     EnfantGauche [6]
                0.08    0.00 108367450/108367450     EnfantDroite [7]
                             100867451             Tamiser_max_rec [2]
-----------------------------------------------
```

###Profilage du programme avec la fonction itérative ($5000000$ entiers)

```c
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
 58.96      0.77     0.77  7499999     0.00     0.00  Tamiser_max
 19.14      1.02     0.25 105867450     0.00     0.00  Echange
 10.72      1.16     0.14 211183123     0.00     0.00  EnfantGauche
  3.06      1.20     0.04        1    40.13    40.13  ConstruireTableau
  3.06      1.24     0.04        1    40.13    40.13  EcrireFichier
  3.06      1.28     0.04        1    40.13    40.13  GetNombreElements
  2.30      1.31     0.03                             AfficherTableau
  0.00      1.31     0.00        1     0.00   383.94  ConstruireTas
  0.00      1.31     0.00        1     0.00     0.00  OuvrirFichier
  0.00      1.31     0.00        1     0.00   779.72  TriTas
```

####Graphe d'appel pour la fonction `Tamiser_max`

```c
granularity: each sample hit covers 2 byte(s) for 0.76% of 1.31 seconds

index % time    self  children    called     name
                                                 <spontaneous>
                0.26    0.13 2500000/7499999     ConstruireTas [4]
                0.51    0.25 4999999/7499999     TriTas [3]
[2]     87.6    0.77    0.38 7499999         Tamiser_max [2]
                0.24    0.00 100867451/105867450     Echange [5]
                0.14    0.00 211183123/211183123     EnfantGauche [6]
-----------------------------------------------
```

###Commentaires

Le nombre d'appel entre la fonction récursive et itérative pour le programme est toujours le même, soit $7499999$ appels, ce qui correspond à $2500000$ appel par `Construire_Tas` et $4999999$ par `TriTas`.
En revanche, la fonction récursive est appelée par elle même $100867451$ fois, ce qui correspond à un coût en temps conséquent, comparé à la fonction itérative, d'où le gain de temps opéré par cette dernière.

La fonction `Echange` est appelée le même nombre de fois entre les deux types de fonction, car les conditions de l'appel sont les mêmes (sans compter les appels par la fonction `TriTas`, qui sont également identiques).

Ce qui est intéressant de constater, c'est que les fonctions `EnfanGauche` et `EnfantDroite` sont appelées un grand nombre de fois. Ces fonctions permettent certes de globaliser la recherche des enfants d'une racine, en ne faisant le calcul qu'une fois (dans la fonction), mais qui en contrepartie coûte cher en temps de calcul. 

La fonction `EnfanGauche` est appelée plus souvent dans la fonction itérative, car elle fait partie de la condition de la boucle, et de la recherche du premier enfant pour déterminer le max. En contrepartie, il n'y a pas d'appel à la fonction `EnfantDroite`, car il suffit d'ajouter un $+1$ lors du test du plus grand enfant. Dans la fonction récursive en revanche, les deux fonctions sont appelées un nombre égal de fois.

#Problèmes rencontrés

Ne pas se tromper dans les index (taille du tableau, position du compteur, position des enfants) à été la principale difficultée du programme. Ce qui explique pourquoi les fonctions `EnfanGauche` et `EnfantDroite` ont été codée, dans le but de faciliter la recherche des enfants, car on est sûr de ne pas se tromper dans les index si on englobe le calcul dans une fonction qu'on utilise partout.

La fonction itérative a été plus difficile à coder que la fonction récursive, du fait qu'elle soit moins intuitive, même si plus performante. 

#Améliorations possibles

Il serait facile d'améliorer le programme en supprimmant les fonctions `EnfanGauche` et `EnfantDroite`, qui coûtent plus cher en temps qu'un simple calcul mathématique directement dans la fonction. Sur un faible nombre d'entier, cela est totalement négligeable, mais sur un plus grand nombre, la différence en temps de calcul commence à se faire voir.

Une amélioration possible de la fonction récursive en tail queue recursion (récursion terminale) serait envisageable, pour que celle-ci soit "transformée" en fonction itérative par le compilateur. Du point de vue code, la fonction serait plus compréhensible, et d'un point de vue exécution, plus performante (autant que si on avait codé directement une fonction itérative).